import Head from 'next/head';
import React from 'react';

const TitleHeader = ({ titlePage }: { titlePage: string }) => {
  return (
    <>
      <Head>
        <title>{titlePage}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  );
};

export default TitleHeader;
