import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { API } from '../client/config';
import Contact from '../components/Contact';
import Cta from '../components/CTA/Cta';
import Section2 from '../components/CTA/Section2';
import Footer from '../components/Footer/Footer';
import MobileNav from '../components/Navbar/MobileNav';
import Rides from '../components/Rides/Rides';
import Rooms from '../components/Rooms/Rooms';

export interface RidesAndRoomTypes {
  rooms: {
    id: string;
    name: string;
    image_url: string[];
    price: number;
    bedtype: string[];
    number_of_guests: number;
    bedrooms: number;
    beds: number;
    bathrooms: number;
    amenities: string[];
    description: string;
  }[];
  rides: {
    id: string;
    name: string;
    description: string;
    image_url: {
      url: string;
    }[];
    price: number;
  }[];
}

const Home: NextPage<RidesAndRoomTypes> = ({ rooms, rides }) => {
  return (
    <>
      <Head>
        <title>Dahilayan</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='section-center'>
        {/* <DesktopNav /> */}
        <Cta />
        <Section2 />
        <Rooms rooms={rooms} />
        <Rides rides={rides} />
        <Contact />
        <div className='my-20 md:hidden'></div>
      </main>
      <footer className='hidden bg-black text-white md:block'>
        <Footer />
      </footer>
      <MobileNav />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const [getRooms, getRides] = await Promise.all([
    API.get('rooms/getRooms'),
    API.get('rides/getRides'),
  ]);

  const [rooms, rides] = await Promise.all([
    getRooms.data.rooms,
    getRides.data.rides,
  ]);

  return {
    props: { rooms, rides },
  };
};
